---
title: "Simulations_WL"
author: "Wenhan Lu"
output: html_document
---
##Install Packages

```{r,warning=FALSE,message=FALSE}
#Check the package 'crrSC', if it does not exist in the environment, then install it.
if (!require("crrSC")) install.packages("crrSC")
library(crrSC)

#Check the package 'parallel', if it does not exist in the environment, then install it.
if (!require("parallel")) install.packages("parallel")
library(parallel)

#Check the package 'numbers', if it does not exist in the environment, then install it.
if (!require("numbers")) install.packages("numbers")
library(numbers)

#Check the package 'mvtnorm', if it does not exist in the environment, then install it.
if (!require("mvtnorm")) install.packages("mvtnorm")
library(mvtnorm)

#Check the package 'survival', if it does not exist in the environment, then install it.
if (!require("survival")) install.packages("survival")
library(survival)

#Check the package 'frailtypack', if it does not exist in the environment, then install it.
if (!require("frailtypack")) install.packages("frailtypack")
library(frailtypack)
```



##Generate Survival mydata1 using Frailty Model.Gamma Distribution 


###Parameters

```{r}
set.seed(12345)
m<-500 #number of simulations

n<-5500 #number of subjects in the simulated data set

beta<-log(0.8) #coefficient of treatment effect in cox model, define hazard ratio=0.8 then exp(beta)=0.8

q<-40/12 #length of follow-up, the follow-up time is 40 months, so 40/12 is follow-up time in year, it is also the cutoff time point for administrative censoring

event<-0.14 #annual event rate

drop<-0.03 #annual drop-off rate

clstr<-80 #number of clusters

dropall<-drop*(1+(1-event-drop)+(1-event-drop)^2+(1/3)*(1-event-drop)^3) #overall drop-off rate for 40 months

result<-matrix(,m,10)

colnames(result) <- c("fall","censoring","dropoff","cutoff","tau1","tau2","rho1","rho2","cox.coef","frailty.coef")

```

###Simulations
```{r}
pb<-txtProgressBar(min=0,max=m,style=3)

for (j in 1:m) {

y<-rnorm(n) #draw random values from standard normal distribution
u<-pnorm(y) 

cluster<-sample(1:clstr,n,replace=TRUE,prob = runif(clstr,0.1,0.9)) #generate cluster indicator with random cluster size

mydata1 <- data.frame(u,cluster)

tau<-0.05 #Kendall's tau, which is used to measure the dependence within cluster. if a is the shape parameter of gamma distribution, tau=1/(2*a+1)
a<-0.5*(1/tau-1)

b<-a #let rate parameter=shape parameter in order to make mean of frailty (gamma random values)=1

z<-rgamma(clstr,a,b) #generate the frailty for each cluster

temp <- data.frame(cluster = 1:clstr,z)

lambda<-b/((1-event)^(1/a))-b #calculate lambda for exponential distribution

theta<-(0.5/(dropall*lambda))*(1+1/exp(beta))*(b/a) #calcualte parameter for drop-off censoring

mydata1$x <- mydata1$cluster%%2

mydata1 <- merge(mydata1,temp,by = 'cluster',all.x = T)

mydata1$time_t<-(-(log(mydata1$u))/(exp(mydata1$x*beta)*mydata1$z*lambda)) #generate the event time from an exponential distribution

#generate observed time (which we will use in analysis) and censoring indicator based on event time, drop-off censoring, and administrative censoring
mydata1$time_c <- runif(n,min=0,max=theta)
mydata1$time_o <- apply(mydata1[,5:6],1,min)
mydata1$status1 <- as.integer(mydata1$time_o == mydata1$time_t)
mydata1$status2 <- as.integer(mydata1$time_o <= q)
mydata1$time_o[!mydata1$status2] <- q
mydata1$status <- mydata1$status1*mydata1$status2

#status is the indicator of censoring for observed time. status=1 means event; status=0 means censoring

##### now the simulated mydata1 set is done #####
##### below is for checking #####


##################################
########### checking #############
##################################

##### check event and censoring rates #####

fall<-mean(mydata1$status) #the actual overall fall rate
censoring<-1-mean(mydata1$status) #the actual overall censoring rate, which is the combination of drop-off and cut-off rate
dropoff<-1-mean(mydata1$status1) #the drop-off rate
cutoff<-1-mean(mydata1$status2) #the administrative censoring rate


##### check denpendence #####


temp1 <- t(sapply(1:clstr,function(i){sample(mydata1[mydata1$cluster==i,5],2,replace=F)}))
sample1 <- data.frame(temp1,cluster = 1:clstr,censoring = rep(c(1,0),clstr/2))
temp2 <- t(sapply(1:clstr,function(i){sample(mydata1[mydata1$cluster==i,7],2,replace=F)}))
sample2 <- data.frame(temp2,cluster = 1:clstr,censoring = rep(c(1,0),clstr/2))

tau1<-cor(sample1[,1:2],method = "kendall")[1,2]  
tau2<-cor(sample2[,1:2],method = "kendall")[1,2]  

rho1<-cor(sample1[,1:2],method = "pearson")[1,2]
rho2<-cor(sample2[,1:2],method = "pearson")[1,2]

##### check predicted Hazard Ratio #####

s<-Surv(mydata1$time_o,mydata1$status)

model1<-coxph(s~as.factor(mydata1$x))

model2<-frailtyPenal(s~as.factor(mydata1$x)+cluster(mydata1$cluster),n.knots = 7,kappa = 10000, data=mydata1, RandDist = "Gamma",maxit=50)

result[j,]<-c(fall,censoring,dropoff,cutoff,tau1,tau2,rho1,rho2,model1$coef,model2$coef)
setTxtProgressBar(pb,j)
}

```


